import Head from 'next/head'
import WorkCategories from '../components/WorkCategories'

export default function Home() {
  return (
    <>
      <Head>
        <title>Alphonse Pierre - Writing</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        <div className="mx-auto max-w-4xl">
          <WorkCategories />
        </div>
      </div>
    </>
  )
}
